name: image_blend_composites_example
description: A image_blend_composites example.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  blend_composites:
    path: ../../blend_composites
  image_blend_composites:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/A.png
    - images/B.png
